my_fifth_project/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('create/', views.create, name='create'),

]

todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
]

todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_todo/', views.create_todo, name='create_todo'),
    path('<int:todo_pk>/', views.detail, name='detail'),
    path('new_todo/', views.new_todo, name='new_todo'),
    path('<int:todo_pk>/delete/', views.delete_todo, name='delete_todo'),
    path('<int:todo_pk>/update_todo/', views.update_todo, name='update_todo'),
    path('<int:todo_pk>/edit_todo/', views.edit_todo, name='edit_todo'),
]

urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]


django_ws_4_c/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()

django_ws_5_c/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()
    created_at = models.DateField(auto_now_add=True)

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.work} : {self.content}"
    
    def __repr__(self):
        return super().__repr__()

todos/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = '__all__'

django_ws_4_c/todos/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    work = request.GET.get('work')
    context = {
        'work': work
    }
    return render(request, 'todos/index.html', context)

def create_todo(request):
    return render(request, 'todos/create_todo.html')

def detail(request, work):
    context = {
        'work': work
    }
    return render(request, 'todos/detail.html', context)

django_ws_5_c/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todo_list = Todo.objects.all()
    context = {
        'todo_list': todo_list
    }
    return render(request, 'todos/index.html', context)

def create_todo(request):
    return render(request, 'todos/create_todo.html')

def detail(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo
    }
    return render(request, 'todos/detail.html', context)

def new_todo(request):
    work = request.POST.get('work')
    content = request.POST.get('content')
    is_completed = False

    todo = Todo(work=work, content=content, is_completed=is_completed)
    todo.save()
    return redirect('todos:detail', todo.pk)

def delete_todo(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    todo.delete()
    return redirect('todos:index')


def update_todo(request, todo_pk):
    # todo 수정 위한 페이지 응답 및 실제 수정 처리
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo
    }
    return render(request, "todos/update_todo.html", context)


def edit_todo(request,todo_pk):
        
    # 사용자가 요청한대로 DB 수정
    todo = Todo.objects.get(pk=todo_pk)
    todo.work = request.POST.get("work")
    todo.content = request.POST.get("content")
    todo.save()

    return redirect('todos:detail',todo.pk)

todos/views.py
from django.shortcuts import render, redirect
from .models import Todo
from .forms import TodoForm

# Create your views here.
def index(request):
    todo_list = Todo.objects.all()
    context = {
        'todo_list': todo_list
    }
    return render(request, 'todos/index.html', context)

def create_todo(request):
    context = {
        "form": TodoForm()
    }
    return render(request, 'todos/create_todo.html',context)

def detail(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo
    }
    return render(request, 'todos/detail.html', context)

def new_todo(request):
    work = request.POST.get('work')
    content = request.POST.get('content')
    is_completed = False

    todo = Todo(work=work, content=content, is_completed=is_completed)
    todo.save()
    return redirect('todos:detail', todo.pk)

def delete_todo(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    todo.delete()
    return redirect('todos:index')

def update_todo(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo
    }
    return render(request, 'todos/update_todo.html', context)

def edit_todo(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)

    work = request.POST.get('work')
    content = request.POST.get('content')

    todo.work = work
    todo.content = content
    todo.save()

    return redirect('todos:detail', todo.pk)

todos/templates/todos/create_todo.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>

  <form action="{% url "todos:new_todo" %}" method="POST">
    {% csrf_token %}

    <input type="submit" value="제출">
  </form>
{% endblock content %}

todos/templates/todos/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 상세 페이지</h1>
  <hr>
  <p>{{ todo.pk }}번 째 할 일</p>
  <p>할 일 : {{ todo.work }}</p>
  <p>내 용 : {{ todo.content }}</p>
  <p>일 자 : {{ todo.created_at }}</p>
  <p>완 료 : {{ todo.is_completed }}</p>
  <hr>
  <a href="{% url "todos:update_todo" todo.pk %}">수정</a>
  <form action="{% url "todos:delete_todo" todo.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
{% endblock content %}

todos/templates/todos/index.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 관리 프로젝트 메인 페이지</h1>
  <p>이 곳에서 할 일 목록을 관리합니다.</p>
  <ul>
    {% for todo in todo_list %}
      <li>
        <input type="checkbox" value="{{ todo.is_completed }}" {% if todo.is_completed %}checked{% endif %}>
        <a href="{% url "todos:detail" todo.pk %}">{{ todo.work }}</a>
      </li>
    {% empty %}
      <li>아직 할 일이 없습니다.</li>
    {% endfor %}
  </ul>
{% endblock content %}

todos/templates/todos/update_todo.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>

  <form action="{% url "todos:edit_todo" todo.pk %}" method="POST">
    {% csrf_token %}
    <label for="work">work : </label>
    <input type="text" name="work" id="work" value="{{ todo.work }}"> <br>
    <label for="content">content : </label>
    <textarea name="content" id="work" cols="30" rows="10">{{ todo.content }}</textarea>
    <input type="submit" value="제출">
  </form>
{% endblock content %}