articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create')
]

my_fifth_project/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('create/', views.create, name='create'),

]

todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
]

urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]


articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateField(auto_now=True)
    updated_at = models.DateField(auto_now=True)

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

def index(request):
	articles = Article.objects.all()
	return render(request, 'articles/index.html', {'articles': articles})

def create(request):
	if request.method == 'POST':
		title = request.POST.get('title')
		content = request.POST.get('content')
		Article.objects.create(title=title, content=content)
		return redirect('articles:index')
	return render(request, 'articles/create.html', {'articles': create})


templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
	<h1>게시글 상세 페이지</h1>
	<p>제목: {{ article.title }}</p>
	<p>내용: {{ article.content }}</p>
	<p>작성일: {{ article.created_at }}</p>
	<p>수정일: {{ article.updated_at }}</p>
		<form action="{% url 'articles:delete' article.pk %}" method="POST" style="display:inline;">
			{% csrf_token %}
			<button type="submit">[DELETE]</button>
		</form>
	<a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}

templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>메인 페이지</h1>
  <a href="{% url 'articles:new' %}">[CREATE]</a>

  <ul>
    {% for article in articles %}
      <li>{{ article.pk }}번째 글</li>
      <li>제목 : {{ article.title }}</li>
      <a href="{% url 'articles:detail' article.pk %}">[DETAILS]</a>
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}

templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>게시글 생성 페이지</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title"> <br>
    <label for="content">내용:</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea><br>

    <input type="submit" value="CREATE">
  </form>
  <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}